"""Ansible role generator."""

from pathlib import Path
from typing import Any

import yaml
from cli2ansible.domain.models import Role
from cli2ansible.domain.ports import RoleGeneratorPort


class AnsibleRoleGenerator(RoleGeneratorPort):
    """Generates Ansible role directory structure."""

    def generate(self, role: Role, output_path: str) -> None:
        """Generate role directory structure."""
        base = Path(output_path)
        base.mkdir(parents=True, exist_ok=True)

        # Create directory structure
        (base / "tasks").mkdir(exist_ok=True)
        (base / "handlers").mkdir(exist_ok=True)
        (base / "vars").mkdir(exist_ok=True)
        (base / "defaults").mkdir(exist_ok=True)
        (base / "meta").mkdir(exist_ok=True)
        (base / "molecule").mkdir(exist_ok=True)

        # Generate tasks/main.yml
        self._generate_tasks(role, base / "tasks" / "main.yml")

        # Generate handlers/main.yml
        self._generate_handlers(role, base / "handlers" / "main.yml")

        # Generate vars/main.yml
        self._generate_vars(role, base / "vars" / "main.yml")

        # Generate defaults/main.yml
        self._generate_defaults(role, base / "defaults" / "main.yml")

        # Generate meta/main.yml
        self._generate_meta(role, base / "meta" / "main.yml")

        # Generate README.md
        self._generate_readme(role, base / "README.md")

        # Generate Molecule scenario
        self._generate_molecule(role, base / "molecule")

    def _generate_tasks(self, role: Role, output_file: Path) -> None:
        """Generate tasks file."""
        tasks_data: list[dict[str, Any]] = []
        for task in role.tasks:
            task_dict: dict[str, Any] = {"name": task.name, task.module: task.args}
            if task.become:
                task_dict["become"] = True
            if task.changed_when:
                task_dict["changed_when"] = task.changed_when
            if task.creates:
                task_dict["args"] = {**task.args, "creates": task.creates}
            if task.removes:
                task_dict["args"] = {**task.args, "removes": task.removes}
            if task.tags:
                task_dict["tags"] = task.tags
            tasks_data.append(task_dict)

        with open(output_file, "w") as f:
            yaml.dump(tasks_data, f, default_flow_style=False, sort_keys=False)

    def _generate_handlers(self, role: Role, output_file: Path) -> None:
        """Generate handlers file."""
        handlers_data = []
        for handler in role.handlers:
            handler_dict = {"name": handler.name, handler.module: handler.args}
            handlers_data.append(handler_dict)

        with open(output_file, "w") as f:
            if handlers_data:
                yaml.dump(handlers_data, f, default_flow_style=False, sort_keys=False)
            else:
                f.write("---\n# Handlers\n")

    def _generate_vars(self, role: Role, output_file: Path) -> None:
        """Generate vars file."""
        with open(output_file, "w") as f:
            if role.vars:
                yaml.dump(role.vars, f, default_flow_style=False, sort_keys=False)
            else:
                f.write("---\n# Variables\n")

    def _generate_defaults(self, role: Role, output_file: Path) -> None:
        """Generate defaults file."""
        with open(output_file, "w") as f:
            if role.defaults:
                yaml.dump(role.defaults, f, default_flow_style=False, sort_keys=False)
            else:
                f.write("---\n# Default variables\n")

    def _generate_meta(self, role: Role, output_file: Path) -> None:
        """Generate meta file."""
        meta = role.meta or {
            "galaxy_info": {
                "author": "cli2ansible",
                "description": f"Generated role: {role.name}",
                "license": "MIT",
                "min_ansible_version": "2.9",
                "platforms": [{"name": "Ubuntu", "versions": ["all"]}],
            }
        }
        with open(output_file, "w") as f:
            yaml.dump(meta, f, default_flow_style=False, sort_keys=False)

    def _generate_readme(self, role: Role, output_file: Path) -> None:
        """Generate README."""
        content = f"""# {role.name}

Generated by cli2ansible

## Description

This role was automatically generated from terminal session commands.

## Tasks

This role contains {len(role.tasks)} tasks:

"""
        for i, task in enumerate(role.tasks, 1):
            content += f"{i}. {task.name} (module: `{task.module}`, confidence: {task.confidence.value})\n"

        content += (
            """
## Usage

```yaml
- hosts: all
  roles:
    - """
            + role.name
            + """
```

## Testing

Run Molecule tests:

```bash
molecule test
```
"""
        )
        with open(output_file, "w") as f:
            f.write(content)

    def _generate_molecule(self, role: Role, output_dir: Path) -> None:
        """Generate Molecule test scenario."""
        default_dir = output_dir / "default"
        default_dir.mkdir(parents=True, exist_ok=True)

        # molecule.yml
        molecule_config = {
            "dependency": {"name": "galaxy"},
            "driver": {"name": "docker"},
            "platforms": [
                {
                    "name": "instance",
                    "image": "geerlingguy/docker-ubuntu2204-ansible:latest",
                }
            ],
            "provisioner": {"name": "ansible"},
            "verifier": {"name": "ansible"},
        }
        with open(default_dir / "molecule.yml", "w") as f:
            yaml.dump(molecule_config, f, default_flow_style=False, sort_keys=False)

        # converge.yml
        converge = [
            {
                "name": "Converge",
                "hosts": "all",
                "tasks": [
                    {"name": "Include role", "include_role": {"name": role.name}}
                ],
            }
        ]
        with open(default_dir / "converge.yml", "w") as f:
            yaml.dump(converge, f, default_flow_style=False, sort_keys=False)

        # verify.yml
        verify = [
            {
                "name": "Verify",
                "hosts": "all",
                "tasks": [{"name": "Example assertion", "assert": {"that": True}}],
            }
        ]
        with open(default_dir / "verify.yml", "w") as f:
            yaml.dump(verify, f, default_flow_style=False, sort_keys=False)
